apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: tsundata/gateway:cc2bd39921bde9564a627a79f28b6239000920ba
          ports:
            - containerPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: tsundata/message:cc2bd39921bde9564a627a79f28b6239000920ba
          ports:
            - containerPort: 5000
