name: docker

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          install-only: true

      - name: Build
        run: make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push gateway
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/gateway/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gateway:${{ github.sha }}

      - name: Build and push message
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/message/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/message:${{ github.sha }}
